name: khp
dependencies:
  - python=3.7
  - pytz==2018.5
  - pandas==0.23.4
  - pyyaml==3.13
  - boto3==1.9.7
  - requests==2.19.1
  - pip:
    - pyfiglet==0.7.5
    - git+https://github.com/ian-whitestone/postgrez.git