name: khp
dependencies:
  - python=3.7
  - dask==0.19.2
  - pytz==2018.5
  - pyyaml==3.13
  - boto3==1.9.7
  - requests==2.19.1
  - pip:
    - glom==18.3.1
    - pyfiglet==0.7.5
    - git+https://github.com/ian-whitestone/postgrez.git
